services:
  nucleus_notifications:
    container_name: nucleus_notifications
    image: nucleus_notifications
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    mem_limit: 1g
    cpus: "2.0"
